"""add factory create method to RefreshToken

Revision ID: 480cc5c632a8
Revises: 601af1ab9bce
Create Date: 2025-09-12 10:20:48.729984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480cc5c632a8'
down_revision: Union[str, Sequence[str], None] = '601af1ab9bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
