"""add like and dislike count to movie

Revision ID: 9f4b3b3fafcd
Revises: a9b6a5b660a1
Create Date: 2025-09-22 11:27:37.193625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4b3b3fafcd'
down_revision: Union[str, Sequence[str], None] = 'a9b6a5b660a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
