[project]
name = "online-cinema-project"
version = "0.1.0"
description = "A FastAPI project that allows users to select, watch, and purchase access to movies as well as manage their accounts."
authors = [
    {name = "Olha",email = "olgazinevych@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[tool.poetry]
packages = [{include = "online_cinema_project", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
